Erick: Tarea 1
lbenet/2020-2-TSelFisicaComputacional-1 pull request #13
Opened 2020-03-26 15:36 UTC by erick-ghz

2020-03-26 15:51 UTC, lbenet commented
Gracias por enviar avances de la Tarea1. Hay algunos comentarios (antes de empezar a leer la tarea). Creaste la carpeta Tarea1 en el directorio principal del curso. La idea es que ese directorio esté en "tareas/".

Lo que te conviene en este caso es lo siguiente (asumo que estás la rama en la que trabajas la tarea1, y en el directorio principal):
```
    $ mkdir tareas/Erick
    $ git mv Tarea1/Tarea-1.jmd tareas/Erick/Tarea-1.jmd
    $ git commit -m "Pongo la Tarea1 en mi subdir en tareas/"
    $ rmdir Tarea1/
```

2020-03-26 18:40 UTC, lbenet reviewed
Hay algunas erratas en lo que escribes en los ejercicios. Además, añadí además un par de comentarios de estilo de programación en Julia. Faltan los ejercicios 3 y 4, y una parte del 2.
Buen comienzo!

2020-03-26 18:40 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +$$ zy = x \quad\text{y}\quad z' = zy' + z'y $$
En la segunda ecuación hay una errata: debe decir x' = zy' + z'y

2020-03-26 18:40 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +Haciendo la analogía de la notación funcional de $f'$ como la derivada de $f$, si $z = \frac{x}{y}$, entonces $z'$ es la derivada de $z'$ dada por la regla del cociente de $\left(\frac{x}{y}\right)'
Dice: "entonces $z'$ es la derivada de $z'$ dada por la regla ... " y debe decir "entonces $z'$ es la derivada de $z$ dada por la regla..."

2020-03-26 18:40 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +```
Esta celda se puede borrar.

2020-03-26 18:40 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +    end
Dos comentarios: lo que haces es correcto, pero no es "elegante" ("juliano"). En este caso, puedes evitar el constructor interno (ya que en realidad no haces "nada particular"); el chequeo de que `x` y `y` son de longitud 1, si bien no hace daño tampoco aporta nada, ya que `x` y `y` son "escalares" de tipo `T<:Real`.

2020-03-26 18:40 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +z = Dual(5.0,4)
Esto da un error, dado que `x` y `y` tienen *ambos* que ser del mismo tipo; las siguientes celdas, entonces dan errores. Para evitar este error, es decir, imponer que `x` y `y` sean *ambos* del tipo `T` cuando no lo son, puedes usar [`promote`](https://docs.julialang.org/en/v1.3/manual/conversion-and-promotion/#).

Si usas `z = Dual(5.0, 2.2)` (de tal manera que ambos son del tipo `Float64`), todo funciona; aún así, es mejor corregir el error

2020-03-26 18:40 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +    /(z::Dual, w::Dual) = Dual(z.x/w.x, ((w.x *z.y) - (z.x * w.y))/(w.x)^2)
Los paréntesis internos no son necesarios (y de hecho, no son recomendables). Entonces, `*` lo puedes escribir
```julia
*(z::Dual, w::Dual) = Dual( z.x * w.x, z.x * w.y + z.y * w.x )
```
Lo mismo se aplica para `/`

2020-03-27 16:10 UTC, lbenet commented
Trata por favor de subir la tarea completa durante el día, para que yo vaya dándo retroalimentación, si es que se necesita.

2020-03-28 01:33 UTC, lbenet commented
La  tarea me aparece vacía, en particular respecto a lo que habías hecho en los commits anteriores.

2020-03-28 01:50 UTC, erick-ghz commented
¿Se sigue con el mismo problema con el último commit?

2020-03-28 01:51 UTC, lbenet commented
Creo que no; sí veo algunos cambios. Dame un rato para revisarla...

2020-03-28 02:14 UTC, lbenet reviewed
Te envié varios comentarios, dos (creo) son opcionales. Vas bien, pero falta acabar dos ejercicios.

2020-03-28 02:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +```
Esta celda, si quieres, la puedes borrar. 

*Comentario opcional*.

2020-03-28 02:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +    /(z::Dual, w::Dual) = Dual(z.x/w.x, ((w.x *z.y) - (z.x * w.y))/(w.x)^2)
Este comentario previo (para `*` y `/`) no lo implementaste; lo dejo abierto.

(Por cierto, no es necesaria la indentación; no es python.)

2020-03-28 02:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +Dual(x::T) where {T <: Real} = Dual(promote(x, 0.0)...)
El código es correcto; pero es más sencillo (y rápido) escribirlo `Dual(x::T) where {T <: Real} = Dual(x, zero(x))`. Vale la pena cambiarlo.

2020-03-28 02:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +    /(z::T, w::Dual) where {T <: Real} = Dual(z) / w
Dos comentarios:
- No es necesario volver a importar las funciones que ya importaste arriba, por lo que debes borrar los `import Base:...` que ya aparecen arriba.
- Si bien es correcto lo que hiciste, es mejor (rápidez) en ocasiones ser explícito. Por ejemplo, 
    ```julia
    +(z::Dual, w::T) where {T <: Real} = Dual( z.x + w, z.y)
    +(z::T, w::Dual) where {T <: Real} = Dual( w + z.x, z.y)
     ```
    De esta manera te evitas sumar o multiplicar por ceros. *Comentario opcional*.

2020-03-28 02:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +promote_rule(::Type{T}, ::Type)
Este inciso de la tarea falta. La idea es verificar casos concretos. Lo que aparece en la celda no hace nada.

2020-03-28 02:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +var_dual(x0::T) where {T <: Real} = Dual(x0, 1)
Aquí falta aún la parte interesante del ejercicio.

2020-03-28 02:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
Vas bien; sólo falta completar este inciso.

2020-03-28 03:53 UTC, erick-ghz commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +Dual(x::T) where {T <: Real} = Dual(promote(x, 0.0)...)
La identación que le pongo es por mero estilo.

2020-03-28 16:03 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +Dual(x::T) where {T <: Real} = Dual(promote(x, 0.0)...)
Pero es "estilo python", no Julia ;-)

2020-03-29 21:27 UTC, lbenet requested changes
Te dejé varios comentarios sobre el archivo `.jmd`; todos son opcionales aunque recomendables. 

En el último commit incluiste el archivo `.ipynb` que no debe incluirse. Entonces te dejo que lo borres. Es este punto el que hace que aún no quede aceptada tu tarea.

2020-03-29 21:27 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +d3/a, d4/b
Lo que hiciste está bien. Una manera de checar que lo que esperas si se cumple es usando `==` o `@assert`, para lo que necesitas sobrecargar `==`. Así, por ejemplo, una vez habiendo sobrecargado (correctamente) `==` podrías usar:
```julia
a + u == Dual(10.0, 42.0)
@assert a*d1 == Dual(100.0, 420.0)
```

2020-03-29 21:27 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
>  ```
Esto es correcto; en este caso podrías hacerlo: `var_dual(x0) = Dual(x0, one(x0))`

2020-03-29 21:27 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +vec == vec1
Como señalé arriba, necesitas sobrecargar `==` para que funcione al comparar dos duales. Pero, es cierto que por los errores de trabajar con aritmética del punto flotante `==` no es suficiente; en ese caso es además bueno sobrecargar `≈` (`Base.isapprox`).

2020-03-29 21:27 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +
Ser cercano a cero se puede cuantificar, en particular en el sentido de cómputo científico. De hecho, una manera sencilla de hacerlo, sin entrar en los detalles, es sobrecargar `≈` (`Base.isapprox`) para dos duales, y entonces hacer `all(vec .≈ vec1)`, esperando que el resultado sea `true`.

2020-03-29 21:27 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +$$  g((x,y)) = (g(x), y\,g'(x)).$$
Excelente!

2020-03-29 21:27 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +L .- L_pr
En todas las comparaciones anteriores se aplica el comentario de usar `≈` que incluí más arriba.

2020-03-31 15:00 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +z / w
Aquí la idea no es mostrar que tu código corre, sino que funciona bien. Entonces, debes sobrecargar `==` para comparar el resultado de una operación con el que esperas. En otras palabras, `Dual(1,-1) + Dual(2, 2) == Dual(3, 1)` debería dar `true`.

2020-03-31 15:14 UTC, lbenet reviewed
Hay varios comentarios aún por abordar, yo diría que menores. En particular, no es lo mismo "imprimir" que verificar (probar, checar, etc).

2020-03-31 15:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +z / w
Este comentario no ha sido abordado aún...

2020-03-31 15:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +d1, d2 = a + u, u - a
Mismo comentario que arriba: tienes que verificar lo que esperas, no sólo imprimirlo.

2020-03-31 15:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +isapprox.(vec, vec1)
El resultado de esto es más sencillo de leer si lo pones `all(vec .≈ vec1)`.

2020-03-31 15:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +isapprox.(vec, vec1)
Este comentario lo puedes usar más abajo...

2020-03-31 15:14 UTC, lbenet commented on tareas/ErickGomez/Tarea1/Tarea-1.jmd
> +isapprox.(V, V_pr)
Mismo comentario que arriba: es mejor `all(V .≈ V_pr)`. Lo mismo se aplica en otras verificaciones abajo

2020-03-31 21:29 UTC, lbenet approved these changes
Gracias por abordar todos los comentarios que dejé antes. La tarea está aprobada, y hago el merge.

2020-03-31 21:29 UTC, merged