Fernanda: Tarea 1
lbenet/2020-2-TSelFisicaComputacional-1 pull request #14
Opened 2020-03-26 15:36 UTC by fernandarr

2020-03-26 18:53 UTC, lbenet commented
Un comentario muy general pero creo que importante: en el primer commit que subiste, se ven avances en la tarea, cosa que no se ve en el segundo commit, que es el "más actual"; imagino que esto no es normal y por eso te lo señalo.

2020-03-26 19:04 UTC, fernandarr commented
Hola Luis. Sí lo qué pasó fue que subí el primer commit y ese es de la
tarea de Samantha, ayer me la mandó pues me estaba ayudando a abrir jupyter
y todo eso. El segundo commit es el mío (que no tiene avances) pero en un
rato subo el mío. Una disculpa


El El jue, 26 de marzo de 2020 a la(s) 12:53, Luis Benet <
notifications@github.com> escribió:

> Un comentario muy general pero creo que importante: en el primer commit
> que subiste, se ven avances en la tarea, cosa que no se ve en el segundo
> commit, que es el "más actual"; imagino que esto no es normal y por eso te
> lo señalo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/14#issuecomment-604620617>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQS4K6SQPITRL7FIECAC7DRJOQDRANCNFSM4LUKLFZQ>
> .
>

2020-03-27 16:10 UTC, lbenet commented
Trata por favor de subir la tarea completa durante el día, para que yo vaya dándo retroalimentación, si es que se necesita.

2020-04-01 19:42 UTC, lbenet commented
@fernandarr Aún no has enviado la  tarea1

2020-04-13 00:27 UTC, lbenet commented
Sigue faltando la tarea1 **completa**; la fecha límite ya pasó, pero te dejo que la entregues finalizada durante lo que queda del día de hoy y mañana.

2020-04-16 22:37 UTC, lbenet requested changes
Añadí 4 comentarios: los importantes (vitales) se refieren al problema 3 y al 4, que no están resueltos. Apúrate a enviar los cambios, porque el tiempo se termina.

2020-04-16 22:37 UTC, lbenet commented on tareas/FRR/Tarea-1.jmd
> +            \Rightarrow z = \frac{x^\prime - z y^\prime}{y} = \frac{x^\prime y - x y^\prime}{y^2}$
Me parece que todo está bien, pero el lado izquierdo de las igualdades en esta línea debería ser z^\prime.

2020-04-16 22:37 UTC, lbenet commented on tareas/FRR/Tarea-1.jmd
>  ```
La idea de `var_dual` es crear  un `Dual` a partir de un valor numérico `x0`, de tal manera que lo podamos identificar con la *variable independiente* en *ése* valor  `x0`.  La función que creaste requiere un Dual, y al ejecutarla da un error. La idea es poderla usar para calcular derivadas en `x0`.

2020-04-16 22:37 UTC, lbenet commented on tareas/FRR/Tarea-1.jmd
>  ```
Este ejercicio está claramente incompleto.

2020-04-16 22:37 UTC, lbenet commented on tareas/FRR/Tarea-1.jmd
> +log(0)
Esto está bien (aunque no entiendo la última línea), *excepto* que no muestra que sale lo que  debe salir. Lo que debes hacer es tomar ejemplos claros y ver que obtienes, al menos de manera aproximada pero con muy buena precisión, el resultado que deberías.

2020-06-01 15:08 UTC, closed without merging