esta es mi tarea 1 samantha
lbenet/2020-2-TSelFisicaComputacional-1 pull request #16
Opened 2020-03-27 03:33 UTC by SamanthaCassab

2020-03-27 16:10 UTC, lbenet commented
Trata por favor de subir la tarea completa durante el día, para que yo vaya dándo retroalimentación, si es que se necesita.

2020-03-27 17:47 UTC, SamanthaCassab commented
Hola luis, iba a preguntar que si cada que guardo mi .ipynb también se
guarda en su versión .jmd o tengo que convertirá cada vez que la vaya a
subir ?
Saludos

El vie., 27 de mar. de 2020 10:10 AM, Luis Benet <notifications@github.com>
escribió:

> Trata por favor de subir la tarea completa durante el día, para que yo
> vaya dándo retroalimentación, si es que se necesita.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/16#issuecomment-605085897>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOWZ6YXDGMS3EB62RNQM4ZDRJTFXHANCNFSM4LUWTQ5Q>
> .
>

2020-03-27 17:50 UTC, lbenet commented
> Hola luis, iba a preguntar que si cada que guardo mi .ipynb también se
guarda en su versión .jmd o tengo que convertirá cada vez que la vaya a
subir ?

Tienes que reactualizar el .jmd usando `convert_doc` de Weave.jl.

2020-03-27 17:51 UTC, lbenet commented
Sin embargo, (y quizás adelantándome) cuando haces `git push` a tu remote y a la rama desde la que hiciste tu PR, eso sí actualiza tu PR.

2020-03-27 18:49 UTC, lbenet reviewed
Te mandé dos comentarios concretos sobre lo que llevas: el primero es quizás un poco exagerado, y el segundo es buena idea tomarlo en cuenta (aunque no es absolutamente necesario) por "estilo" de  programación.

2020-03-27 18:49 UTC, lbenet commented on tareas/sam_tareas/Tarea-1.jmd
> +si expresamos $\overleftrightarrow{z} = \frac{\overleftrightarrow{x}}{\overleftrightarrow{y}} \cdot \frac{\overleftrightarrow{y}^*}{\overleftrightarrow{y}^*} $ donde $ \overleftrightarrow{y}^* $ es c
El ejercicio está correcto y no hay nada que decir. Pero, como no has terminado la tarea, ahí va este comentario exageradamente detallista: las oraciones (nuevas) inician con mayúscula.

2020-03-27 18:49 UTC, lbenet commented on tareas/sam_tareas/Tarea-1.jmd
> +end
En principio, la estructura es correcta en un sentido funcional, como lo muestras en las siguientes celdas. Sin embargo, no entiendo por qué quieres que tu estructura `Dual{T}` sea un subtipo de `AbstractArray{T,1}` (vector). Creo que no es necesario y te evitas algunos inconvenientes, como no necesitar sobrecargar `Base.size` ni `Base.getindex`. Por ejemplo, el constructor interno (líneas 59-62) no sería necesario (es suficiente con declarar los campos internos), y la línea 63 la podrías escribir como un constructor *externo* (a fuera de la `struct`), y se vería: `Dual(x::T) where {T<:Real} = new{T}(x,0)`.

Otra cosa: falta la documentación del tipo Dual (docstrings).

2020-03-27 18:56 UTC, lbenet commented on tareas/sam_tareas/Tarea-1.jmd
> +/(a::Dual, b::Dual) = Dual(a.x/b.x,(b.x*a.y-a.x*b.y)/b.x^2)
Otro comentario: estas operaciones involucran `Dual`es, y son correctas. Sin embargo, vas a requerir sobrecargar operaciones que involucren `Real`es, en el sentido de que te va a interesar cosas como `5*a` o también `b-3`, con `a` un `Dual`, incluyendo `^(a::Dual, n::Int)`.

2020-03-27 21:59 UTC, SamanthaCassab commented on tareas/sam_tareas/Tarea-1.jmd
> +end
Lo había hecho pensando en retringir que el numero dual no fuera una lista por si se podía , pero ya lo corregí y vi que igual jala.
"Otra cosa: falta la documentación del tipo Dual (docstrings). "  esto no lo entiendo

2020-03-27 21:59 UTC, SamanthaCassab commented on tareas/sam_tareas/Tarea-1.jmd
> +/(a::Dual, b::Dual) = Dual(a.x/b.x,(b.x*a.y-a.x*b.y)/b.x^2)
si ya lo tengo gracias

2020-03-27 22:10 UTC, lbenet commented
Recibí tus comentarios, pero no veo los "últimos cambios".

2020-03-27 22:42 UTC, SamanthaCassab commented
ya los pushee pero no los veo..

2020-03-27 22:46 UTC, lbenet commented
El problema, creo, es que hiciste `git push samantha master`; lo que debiste hacer es `git push samantha sam/T1`. Eso nos va a obligar a tener que hacer *git  magic*.

2020-03-27 22:47 UTC, lbenet commented
Dame un momento, y te describo qué tienes que hacer...

2020-03-27 23:08 UTC, lbenet commented
> El problema, creo, es que hiciste git push samantha master; lo que debiste hacer es git push samantha sam/T1. Eso nos va a obligar a tener que hacer git magic.

Esto que dije creo que es incorrecto. Lo que puedo ver en GitHub es que el último commit que subiste fue hace 5 horas. Lo que se me ocurre es que no has hecho `git add` y  `git commit` antes de hacer `git  push`...

2020-03-27 23:13 UTC, SamanthaCassab commented
![Screenshot (182)](https://user-images.githubusercontent.com/61710178/77807674-ce096d00-7045-11ea-9f0c-e9b1d2edb04a.png)

2020-03-27 23:26 UTC, lbenet commented
Gracias por la captura de pantalla. Hay varias cosas que ahí se ven raras. 
- Primero, haz `git restore ../Tarea-1.jmd`; esto evitará dolores de cabeza más tarde. (De otra manera, borrarías un archivo que no debes borrar.)
- Segundo, el remote "origin" apunta a tu propio fork. Lo que debes hacer es:
    ```
    git remote set-url origin https://github.com/lbenet/2020-2-TSelFisicaComputacional-1.git
    ```
    Esto (por ahora) no es grave, pero si no lo corriges no actualizarás tu fork con el curso.
- Tercero, haz algún cambio (aunque sea minúsculo) en `Tareas-1.jmd` y lo salvas (es importante que se detecte algún cambio). Después haces
    ```

Y vemos qué pasa....
    git add Tareas-1.jmd
    git commit -m "Cambio minúsculo"
    git push fork_samantha sam/T1
    ```

2020-03-27 23:43 UTC, SamanthaCassab commented
ya lo hice...
 el git restore "actualiza" ese mismo archivo ?

2020-03-27 23:45 UTC, lbenet commented
Creo que originalmente borraste o moviste el archivo (original) con el enunciado de la tarea. `git restore` debería reestaurar el archivo que borraste.

2020-03-28 01:11 UTC, SamanthaCassab commented
bueno , ya lo intenté varias veces pero no puedo volver a subirlo .
![Screenshot (183)](https://user-images.githubusercontent.com/61710178/77811248-5bed5400-7056-11ea-8f1c-3e9e3c409577.png)

2020-03-28 01:15 UTC, lbenet commented
Hiciste algún cambio en el archivo `sam_tareas/Tarea-1.jmd` ?

En la línea que haces "git commit", `git` responde que no hay cambios nuevos. Por eso cuando subes algo no pasa nada (no hay nada que actualizar).

2020-03-28 01:21 UTC, SamanthaCassab commented
los cambios los hice en Tarea-1.ipynb y los guarde y luego convertí en .jmd

2020-03-28 01:24 UTC, lbenet commented
Edita directamente el archivo Tarea-1.jmd y escribe una frase al principio (luego se puede borrar); el formato del archivo es markdown. Haces entonces `git add Tarea-1.jmd`, `git commit -m "Prueba de cambio irrelevante", y `git push fork_samantha sam/T1`, y vemos qué pasa.

2020-03-28 15:20 UTC, lbenet commented
En lo que subiste no están los ejercicios 3 y 4 resueltos...

2020-03-30 02:43 UTC, lbenet commented
Aparentemente sí hay cambios. La revisaré en un rato...

2020-03-30 03:53 UTC, lbenet requested changes
Dejé 4 comentarios. Dos de ellos tienen que ver con la función `h(x)` que defines en el Ejercicio 3: di qué representa y úsala! Los otros dos son porque hay dos tests que, como están escritos, fallan (uno de ellos es un hint).

2020-03-30 03:53 UTC, lbenet commented on tareas/sam_tareas/Tarea-1.jmd
> +h(x) = (-21x*x*x*x + 112x*x*x -21x*x -6x + 8)/(7x*x*x - 1)^2
Entiendo quien es `h(x)`; aún así, creo que vale la pena escribir por qué lo incluyes aquí (y usarlo).

2020-03-30 03:53 UTC, lbenet commented on tareas/sam_tareas/Tarea-1.jmd
> +g(var_dual(2))
Ya que tienes `h(2)`, por qué no compararlo con `g(2).y`?

2020-03-30 03:53 UTC, lbenet commented on tareas/sam_tareas/Tarea-1.jmd
> +```
Estos dos tests, de hecho, fallan.

2020-03-30 03:53 UTC, lbenet commented on tareas/sam_tareas/Tarea-1.jmd
> +```
Hint: Sobrecarga `Base.isapprox` (`≈`). Para tener una guía, checa cómo está definido en Julia [aquí](https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/base/floatfuncs.jl#L274).

2020-04-01 19:44 UTC, lbenet commented
@SamanthaCassab Recuerda subir la Tarea1 para que sea aceptada; la fecha de aceptación ya pasó.

2020-04-02 22:19 UTC, lbenet approved these changes
Gracias! Aceptada!

2020-04-02 22:19 UTC, merged