Agrego el texto de la tarea a mi carpeta personal.
lbenet/2020-2-TSelFisicaComputacional-1 pull request #5
Opened 2020-03-02 19:23 UTC by carranco-sga

Hola, 

Abro el PR para la primer tarea.

2020-03-13 01:47 UTC, lbenet requested changes
Gracias por enviar la Tarea! He incluido algunos comentarios que son opcionales; hay sin embargo dos que si requieren una revisión pequeña. En particular el que se refiere al ejercicio 3 creo que es importante, y ahí seguramente fue mi redacción la que causó cierta confusión.

2020-03-13 01:47 UTC, lbenet commented on tareas/CSGA/Duales.jl
> +import Base: show, +, -, *, /, sin, cos, tan, ^, sqrt, exp, log
Este comentario es opcional: algo que no se me ocurrió en el momento correcto fue sugerir sobrecargar `==` para poder comparar `Dual` con resultados esperados. Esto tiene interés a la hora de hacer las pruebas.

2020-03-13 01:47 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +Usando esta, podemos determinar las componentes de $\overleftrightarrow{x}^{-1}$ a partir de las componentes de $\overleftrightarrow{x}$ a través de una ecuación algebraica.
"Usando esta," -> "Usando ésta,"

2020-03-13 01:47 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +Dual{Int64}(Dual(1//1, 4//2))
Quizás éste no es un buen ejemplo, en el sentido (general) de que uno no siempre puede convertir un racional a un entero. Ciertamente en tu caso concreto esto sí es posible, pero en general no. Por ejemplo, `Dual{Int64}(Dual(1//3, 1//2))` *debe* dar un error.

2020-03-13 01:47 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +Dual{Int64}(Dual(1//1, 4//2))
Aún así, el punto que quieres comunicar se entiende.

2020-03-13 01:47 UTC, lbenet commented on tareas/CSGA/Duales.jl
> +import Base: show, +, -, *, /, sin, cos, tan, ^, sqrt, exp, log
Mmmm... Checando tus tests veo que en algún sentido ya fue hecho...

2020-03-13 01:47 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +Usando `x = Dual(2.0)`, calcular
Quizás aquí mi redacción fue confusa: La idea es considerar a la variable independiente `x` como un dual, cuya parte principal igual a 2, y entonces evaluar `g(x)`. En algún sentido lo que hiciste es evaluar `g(x)` en el dual (constante) `Dual(2, 0)`. ¿No se si esto hace más claro el obbjetivo del ejercicio?

2020-03-13 02:32 UTC, carranco-sga commented
Gracias por tus comentarios, Luis. Trabajaré en aclarar mis resultados y realizar las correciones.

2020-03-13 05:12 UTC, carranco-sga commented on tareas/CSGA/Duales.jl
> +import Base: show, +, -, *, /, sin, cos, tan, ^, sqrt, exp, log
Lo de sobrecargar ``==`` parece que sería necesario si no marcara a el tipo ``Dual`` como subtipo de ``Number``, en cuyo caso, hay un método definido [usando](https://github.com/JuliaLang/julia/blob/v1.3.1/base/promotion.jl#L348) las reglas de promoción. Lo que me parece curioso es que aún antes de definir las reglas de promoción (cargando sólo la definición del tipo), correr algo como ``Dual(1.0, 1.0) == Dual(1.0, 1.0)`` devuelve ``true`` y algo como ``Dual(1.0, 2.0) == Dual(1.0, 1.0)`` devuelve ``false``. Esto parece ser el caso cuando tenemos tipos más generales, no necesariamente subtipos de ``Number``, como se puede ver con el siguiente ejemplo:

```julia
julia> struct ejemplo; x; end

julia> ejemplo(1) == ejemplo(1)
true

julia> ejemplo(1) == ejemplo(2)
false

julia> ejemplo(1) == ejemplo(1.0)
false

julia> @which ejemplo(1) == ejemplo(1.0)
==(x, y) in Base at operators.jl:83
```

En este caso, resulta que ``==`` ya tiene [un método fallback](https://github.com/JuliaLang/julia/blob/v1.3.1/base/operators.jl#L55) definido en general en términos de ``===``, que hace comparaciones en términos de la [ubicación en memoria](https://github.com/JuliaLang/julia/blob/v1.3.1/base/operators.jl#L196).   (Que personalmente no me queda claro cómo queda definido para tipos definidos por el usuario).

2020-03-13 05:28 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +Usando esta, podemos determinar las componentes de $\overleftrightarrow{x}^{-1}$ a partir de las componentes de $\overleftrightarrow{x}$ a través de una ecuación algebraica.
Corregido el error (horror) de ortografía por [este](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/a095afd0128ff9f8e76fda5b12e7b79a6302d6b7) commit. (Aunque la tilde diacrítica ya no debe ser usada para los [pronombres demostrativos](http://lema.rae.es/dpd/srv/search?id=Adwesaq4ND64VT09xQ#321) según la [RAE], la Academia Mexicana de la Lengua [sigue sugiriendo su uso](https://www.academia.org.mx/espin/respuestas/item/tilde-en-demostrativos).

2020-03-13 05:41 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +Dual{Int64}(Dual(1//1, 4//2))
Tienes razón en que el ejemplo está mal escogido. Lo cambié y traté de aclarar el punto con [este](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/8e0359d74a1228e55d81d630ad7c692be77374b3) commit.

2020-03-13 08:44 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +Usando `x = Dual(2.0)`, calcular
He intentado comentar lo que pasa al permitir variar la parte derivada dejando la parte principal fija. Los resultados los incorporo en [este](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/1e9b3695d7f602779bb650e09b002a18ce7c08e6) commit.

2020-03-13 15:46 UTC, lbenet commented on tareas/CSGA/Duales.jl
> +import Base: show, +, -, *, /, sin, cos, tan, ^, sqrt, exp, log
Por eso el comentario; simplemente, me sorprendió!

2020-03-13 15:47 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +Usando esta, podemos determinar las componentes de $\overleftrightarrow{x}^{-1}$ a partir de las componentes de $\overleftrightarrow{x}$ a través de una ecuación algebraica.
I'm old fashion!

2020-03-13 15:56 UTC, lbenet requested changes
Dos comentarios más de regreso...

2020-03-13 15:56 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +Para facilitarnos el análisis, definamos una función que deje fije igual a dos la parte principal del argumento y permita variar la parte derivada del mismo:
"que deje fije igual a dos" debe ser "que deje igual a dos" o "que dije a dos ..."

2020-03-13 15:56 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +```
Entiendo lo que quieres hacer y no está mal, pero el ejercicio es aún más sencillo. La pregunta concreta es: ¿cómo representar la variable independiente `x`, si su valor es 2? Esencialmente la pregunta es: ¿cuánto vale la derivada de la variable independiente en 2? Espero que esto esté más claro.

Lo que hiciste, que se ve correcto, es justamente variar la parte de la derivada en `x`, cosa que no tiene la misma interpretación de la variable independiente en 2.

2020-03-14 22:55 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +Para facilitarnos el análisis, definamos una función que deje fije igual a dos la parte principal del argumento y permita variar la parte derivada del mismo:
¡Oops! Un error de dedo en medio de una frase poco entendible. ¡Gracias por captarlo! Corregido [aquí](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/2050affcbea6afdabb1b427a65fa4a4edee29faf).

2020-03-14 23:21 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +```
Creo que ya te entiendo, Luis: quieres que veamos qué tipo de argumento dual, ``x``, le tenemos que dar a g para recobrar estar evaluando g en la identidad (de los duales); y después ver qué da el evaluar ``g(x)`` cuando la parte principal de ``x`` es dos.
(Es decir, en lugar de evaluar g en la constante (2, 0) como resultaría al simplemente llamar ``g(Dual(2.0))``, queremos evaluar g en la función identidad (dual) cuando esta vale dos.)

Respecto a esto, me di cuenta que mi justificación para el definir el constructor externo ``Dual(x) = Dual(x, zero(x))`` en el ejercicio 2 está mal en ese contexto. Allí lo que estamos haciendo formalmente es incluir cada valor como constante, y no como el resultado de evaluar la identidad en un punto. (Como creo que quieres que hagamos en el ejercicio 3.) De cualquier manera, corrijo eso en [este](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/4cf740f63fe76082e308698f7d46da4fc26b4eae) commit.

2020-03-14 23:29 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +```
Creo que todavía no; insisto, la culpa seguramente es mi redacción.

Voy a cambiar un poco la notación, para ver si esto es más claro: `x` es un `Dual` que representa a la "variable independiente"; lo importante es lo último. Como es un `Dual`, su parte principal que llamaré `x0` representa el valor de la variable `x`; por otro lado está su parte derivada. La idea de la pregunta es cómo definir la parte derivada) para que `x` represente precisamente la variable independiente, y entonces tenga sentido la pregunta de "cuánto vale `g(x)`?" Espero que esto esté más claro...

2020-03-14 23:32 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +```
Quizás la confusión proviene de que pido definir un método que sólo requiera una entrada (y eso lo hiciste bien), pero más bien es definir otra función `var_Dual(x_0)` cuyo resultado
represente al `Dual` con parte principal en `x_0`, que representa a la variable independiente.

2020-03-15 03:06 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +```
Gracias por la aclaración que realizaste en el enunciado de la tarea. Agrego la solución correspondiente al ejercicio 3 en [este](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/853f247d697d518d9f534afbc584412c7c370168) commit.

2020-03-15 20:39 UTC, lbenet commented on tareas/CSGA/Duales.jl
> +var_Dual(x::T) where {T <: Real} = Dual(x, one(x))
Exacto!

2020-03-15 20:41 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +Para poder enteder más precisamente por qué este es el caso (y de paso ver cómo precisar el valor de $d$), supongamos que $f$  es "suficientemente bonita" y $x_0$ es un punto de su dominio (i.e. que
Este comentario es una exageración: De la siguiente frase, "Para poder enteder más precisamente", yo quitaría el "más".

2020-03-15 20:43 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +En efecto, salvo error, esto concuerda con el [valor esperado](https://www.wolframalpha.com/input/?i=D%5B%283*x%5E2+-+8*x+%2B+1%29%2F%287*x%5E3+-+1%29%2C+x%5D+%2F.+%7Bx+-%3E+2%7D).
Yo escribiría "salvo errores numéricos (de truncación), ..."

2020-03-15 20:45 UTC, lbenet commented on tareas/CSGA/Tarea-1.jmd
> +```
Doy por resuelto este punto. Gracias!

2020-03-15 20:47 UTC, lbenet approved these changes
Dejé un par de comentarios, aunque tu PR está aprobado. Dime si prefieres hacer los cambios o si prefieres que haga el merge.

2020-03-15 20:55 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +Para poder enteder más precisamente por qué este es el caso (y de paso ver cómo precisar el valor de $d$), supongamos que $f$  es "suficientemente bonita" y $x_0$ es un punto de su dominio (i.e. que
Gracias por el comentario, Luis. Se lee mejor como sugieres. Lo incorporo en [este](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/e15fbbdd0c994ad22ef36fefda8e9c20d42d2980) commit.

2020-03-15 20:56 UTC, carranco-sga commented on tareas/CSGA/Tarea-1.jmd
> +En efecto, salvo error, esto concuerda con el [valor esperado](https://www.wolframalpha.com/input/?i=D%5B%283*x%5E2+-+8*x+%2B+1%29%2F%287*x%5E3+-+1%29%2C+x%5D+%2F.+%7Bx+-%3E+2%7D).
En efecto, lo dejé demasiado ambiguo, gracias por precisarlo. Incorporo el cambio en [este](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/e15fbbdd0c994ad22ef36fefda8e9c20d42d2980) commit.

2020-03-15 20:57 UTC, carranco-sga commented
Gracias por todos los comentarios, Luis. He hecho las correciones para que quede más entendible el texto en [este]](https://github.com/lbenet/2020-2-TSelFisicaComputacional-1/pull/5/commits/e15fbbdd0c994ad22ef36fefda8e9c20d42d2980) commit.

2020-03-17 15:21 UTC, lbenet commented
Me parece que todo está bien y es consistente. Haré el "squash and merge" el viernes o el sábado.

2020-03-17 19:32 UTC, carranco-sga commented
Gracias, Luis. Estaré al pendiente.

2020-03-21 17:18 UTC, merged

2020-03-21 17:18 UTC, lbenet commented
Listo! Tarea en el repo!